"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _admin_stats_cards from './admin-stats-cards.bones.json'
import _admin_applications_table from './admin-applications-table.bones.json'

registerBones({
  "admin-stats-cards": _admin_stats_cards,
  "admin-applications-table": _admin_applications_table,
})
